# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    "luks-3787591e-d188-454d-9e91-fe51253f8d2a" = {
      device = "/dev/disk/by-uuid/3787591e-d188-454d-9e91-fe51253f8d2a";
      allowDiscards = true;
      bypassWorkqueues = true;
    };

    "luks-0beae128-36f3-4825-aea4-f1dbf79b88d1" = {
      device = "/dev/disk/by-uuid/0beae128-36f3-4825-aea4-f1dbf79b88d1";
      allowDiscards = true;
      bypassWorkqueues = true;
    };
  };

  swapDevices = [
    {
      device = "/dev/mapper/luks-0beae128-36f3-4825-aea4-f1dbf79b88d1";
      options = [
        "discard"
      ];
    }
  ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-3787591e-d188-454d-9e91-fe51253f8d2a";
    fsType = "btrfs";
    options = [
      "compress=zstd:3"
      "discard=async"
      "space_cache=v2"
      "noatime"
      "commit=60"
      "ssd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-3787591e-d188-454d-9e91-fe51253f8d2a";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd:3"
      "discard=async"
      "space_cache=v2"
      "noatime"
      "commit=60"
      "ssd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-3787591e-d188-454d-9e91-fe51253f8d2a";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd:3"
      "discard=async"
      "space_cache=v2"
      "relatime"
      "commit=60"
      "ssd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3E17-660E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
