# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    "luks-3787591e-d188-454d-9e91-fe51253f8d2a".device = "/dev/disk/by-uuid/3787591e-d188-454d-9e91-fe51253f8d2a";
    "luks-0beae128-36f3-4825-aea4-f1dbf79b88d1".device = "/dev/disk/by-uuid/0beae128-36f3-4825-aea4-f1dbf79b88d1";
  };

  fileSystems."/" =
    { device = "/dev/mapper/luks-3787591e-d188-454d-9e91-fe51253f8d2a";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-3787591e-d188-454d-9e91-fe51253f8d2a";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-3787591e-d188-454d-9e91-fe51253f8d2a";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E17-660E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-0beae128-36f3-4825-aea4-f1dbf79b88d1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
