{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    mangohud
    goverlay
  ];

  environment.variables.MANGOHUD = "1";

  home-manager.users = config.mapAllUsersToSet (user: {
    "${user}".xdg.configFile."MangoHud/MangoHud.conf".text = ''
      ################### File Generated by GOverlay ###################
      custom_text_center=Stats for Nerds

      toggle_fps_limit=F4


      legacy_layout=false
      gpu_stats
      gpu_temp
      gpu_core_clock
      gpu_mem_clock
      gpu_power
      gpu_load_change
      gpu_load_value=50,90
      gpu_load_color=FFFFFF,FF7800,CC0000
      gpu_text=GPU
      cpu_stats
      cpu_temp
      cpu_power
      cpu_mhz
      cpu_load_change
      core_load_change
      cpu_load_value=50,90
      cpu_load_color=FFFFFF,FF7800,CC0000
      cpu_color=2e97cb
      cpu_text=CPU
      io_color=a491d3
      swap
      vram_color=ad64c1
      ram
      ram_color=c26693
      procmem
      procmem_shared
      procmem_virt
      fps
      engine_version
      engine_color=eb5b5b
      gpu_name
      gpu_color=2e9762
      vulkan_driver
      arch
      wine
      wine_color=eb5b5b
      frame_timing=1
      frametime_color=00ff00
      resolution
      battery
      exec=echo #add a line for text space
      exec=echo #add a line for text space
      custom_text=Distro:
      exec=cat /home/torben/.config/goverlay/distroinfo
      custom_text=Version:
      exec=cat /home/torben/.config/goverlay/distroversion
      custom_text=Kernel:
      exec=cat /home/torben/.config/goverlay/kernelversion
      custom_text=Session:
      exec=printf wayland
      media_player_color=ffffff
      background_alpha=0.4
      font_size=31

      background_color=020202
      position=top-left
      text_color=ffffff
      round_corners=10
      toggle_hud=Shift_R+F12
      toggle_logging=Shift_L+F2
      upload_log=F5
      output_folder=/home/torben
      media_player_name=spotify
    '';
  });
}
