{ ... }:

{
  imports = [
    ../../programs/age.nix
    ../../programs/appimage-run.nix
    ../../programs/aria2.nix
    ../../programs/bcachefs-tools.nix
    ../../programs/btop.nix
    ../../programs/btrfs-progs.nix
    ../../programs/cpupower.nix
    ../../programs/cryptsetup.nix
    ../../programs/dfc.nix
    ../../programs/dig.nix
    ../../programs/exfatprogs.nix
    ../../programs/fdisk.nix
    ../../programs/ffmpeg.nix
    ../../programs/fish.nix
    ../../programs/fuse3.nix
    ../../programs/gdisk.nix
    ../../programs/git.nix
    ../../programs/gnu-coreutils-full.nix
    ../../programs/gnumake.nix
    ../../programs/gnutar.nix
    ../../programs/htop.nix
    ../../programs/i2c-tools.nix
    ../../programs/inxi.nix
    ../../programs/jq.nix
    ../../programs/killall.nix
    ../../programs/lm_sensors.nix
    ../../programs/lshw.nix
    ../../programs/lvm2.nix
    ../../programs/mail.nix
    ../../programs/ncdu.nix
    ../../programs/neofetch.nix
    ../../programs/nettools.nix
    ../../programs/nh.nix
    ../../programs/nix-alien.nix
    ../../programs/nix-index.nix
    ../../programs/nix-ld.nix
    ../../programs/nix-output-monitor.nix
    ../../programs/nix-prefetch-github.nix
    ../../programs/nixfmt.nix
    ../../programs/ntfs3g.nix
    ../../programs/nvd.nix
    ../../programs/openssl.nix
    ../../programs/parallel.nix
    ../../programs/parted.nix
    ../../programs/pay-respects.nix
    ../../programs/pciutils.nix
    ../../programs/pigz.nix
    ../../programs/pkg-config.nix
    ../../programs/pkgconf.nix
    ../../programs/ripgrep.nix
    ../../programs/ripgrep-all.nix
    ../../programs/rsync.nix
    ../../programs/rust-stakeholder.nix
    ../../programs/screen.nix
    ../../programs/scrub.nix
    ../../programs/smartmontools.nix
    ../../programs/sops.nix
    ../../programs/speedtest-cli.nix
    ../../programs/sudo-rs.nix
    ../../programs/tldr.nix
    ../../programs/unrar.nix
    ../../programs/unzip.nix
    ../../programs/usbutils.nix
    ../../programs/uwufetch.nix
    ../../programs/vim.nix
    ../../programs/wget.nix
    ../../programs/wine-staging.nix
    ../../programs/xfsprogs.nix
    ../../programs/xz.nix
    ../../programs/yt-dlp.nix
    ../../programs/zip.nix
    ../../programs/zoxide.nix
    ../../programs/zstd.nix
  ];
}
