{ config, pkgs, ... }:

{
  imports = [
    ./appimage-run.nix
    ./aria2.nix
    ./btop.nix
    ./btrfs-progs.nix
    ./cpupower.nix
    ./dfc.nix
    ./dig.nix
    ./fdisk.nix
    ./ffmpeg.nix
    ./fish.nix
    ./fuse3.nix
    ./gdisk.nix
    ./gh.nix
    ./git.nix
    ./gnumake.nix
    ./gnutar.nix
    ./htop.nix
    ./java.nix
    ./killall.nix
    ./llvm.nix
    ./lm_sensors.nix
    ./lshw.nix
    ./mail.nix
    ./neofetch.nix
    ./nix-prefetch-github.nix
    ./nmap.nix
    ./openssl.nix
    ./parallel.nix
    ./parted.nix
    ./pciutils.nix
    ./pkg-config.nix
    ./pkgconf.nix
    ./python3.nix
    ./rsync.nix
    ./rustup.nix
    ./screen.nix
    ./speedtest-cli.nix
    ./thefuck.nix
    ./tldr.nix
    ./unzip.nix
    ./usbutils.nix
    ./uwufetch.nix
    ./vim.nix
    ./wget.nix
    ./xz.nix
    ./zip.nix
    ./zoxide.nix
    ./zstd.nix
  ];
}
